name: "Hello .NET"

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      Notes_Api_Test: "Notes.Api.Test/Notes.Api.Test.csproj"

    steps:
      - uses: actions/checkout@v3

      - name: "Setup .NET Core SDK"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: "Restore Tests"
        run: dotnet restore $Notes_Api_Test

      - name: "Build Tests"
        run: dotnet build --no-restore --configuration Release $Notes_Api_Test

      - name: "Run Tests"
        run: |
          dotnet test \
            --no-build \
            --configuration Release \
            --verbosity normal \
            --logger trx \
            $Notes_Api_Test
      - name: "Report Tests"
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-report
          path: Notes.Api.Test/TestResults/*.trx
          reporter: dotnet-trx
